%%
rng('default')
hiddenSize1 = 100;
autoenc1 = trainAutoencoder(input_full(:,1:50),hiddenSize1, ...
    'MaxEpochs',400, ...
    'L2WeightRegularization',0.004, ...
    'SparsityRegularization',4, ...
    'SparsityProportion',0.15, ...
    'ScaleData', false);