addpath('/home/qg26/map-the-ocean-floor')
addpath('/home/qg26/map-the-ocean-floor/at/Matlab/ReadWrite/')
addpath('/home/qg26/map-the-ocean-floor/at/Matlab/Plot/')
addpath('/home/qg26/map-the-ocean-floor/at/Matlab/')
addpath('/home/qg26/map-the-ocean-floor/at/Matlab/Bellhop/')
addpath('/home/qg26/map-the-ocean-floor/at/Matlab/Arr/')
addpath('/home/qg26/map-the-ocean-floor/NN/')
addpath('/home/qg26/map-the-ocean-floor/generate_files/')
addpath('/home/qg26/map-the-ocean-floor/bump/')
% addpath('/home/qg26/Noise/')
% addpath('/home/qg26/Noise/flat/')
% addpath('/home/qg26/Data/blurred & real  -2~2 0.7~1.8/')